#!/bin/bash

# export ANSICON=true
# export TERM=msys
# C:\Public\SOFTWARE\cmderrs\cmder_mini-1.3.8\vendor\conemu-maximus5\ConEmu\conemu-msys2-64.exe  /usr/bin/bash.exe -c "./echos"

depth=0
infocols="46;97"
warncols="43;30"
errorcols="45;97"
# echo "FROM_DOS='${FROM_DOS}'"
if [[ "${FROM_UNIX}" != "" ]]; then
  infocols="106;30"
  warncols="103;30"
  errorcols="101;30"
fi
function caller() {
  local i=0
  local path
  while [ -n "${BASH_SOURCE[$i]}" ]; do
    path="${BASH_SOURCE[$i]}"
    if [[ "$path" == *"/echos/"* ]]; then
      ((i++))
    else
      break
    fi
  done
  caller="$(basename "$path")"
}
function mlog() { if [[ "${2}" != "" ]]; then eval "${2}=\"\${${2}}\n\${1}\""; fi; }
function spaces() { caller; if [[ ${depth} -gt 0 ]]; then printf %${depth}s; fi; }
function ok() { set +x; spaces; echo -e "\e[42;97m Ok    \e[0m: [${caller}] ${1}" >&3; mlog "ok: ${1}" "${2}"; set -x; }
function info() { set +x; spaces; echo -e "\e[${infocols}m Info  \e[0m: [${caller}] ${1}" >&3; mlog "info: ${1}" "${2}"; set -x; }
function warning() { set +x; spaces; echo -e "\e[${warncols}m Warn  \e[0m: [${caller}] ${1}" >&3; mlog "Warning: ${1}" "${2}"; set -x; }
function task() { set +x; spaces; echo -e "\e[${infocols}m Task\e[0m\e[${warncols}m=>\e[0m: [${caller}] ${1}" >&3; mlog "Task: ${1}" "${2}"; set -x; }
function error() { set +x; spaces; echo -e "\e[${errorcols}m Error \e[0m: [${caller}] ${1}" >&3; mlog "ERROR: ${1}" "${2}"; set -x; }
# shellcheck disable=SC2317
function fatal() { set +x; spaces; echo -e "\e[41;97m FATAL [${2}]\e[0m: [${caller}] ${1}" >&3; exit "${2}"; mlog "FATAL: ${1}" "${3}"; set -x; }

# https://stackoverflow.com/questions/2683279/how-to-detect-if-a-script-is-being-sourced
(return 0 2>/dev/null) && sourced=1 || sourced=0
if [[ "${1}" == "" && ${sourced} -eq 0 ]]; then
  # echo "TERM='${TERM}', ANSICON='${ANSICON}'"
  ok "test bash msg"
  task "test bash msg"
  info "test bash msg"
  warning "test bash msg"
  error "test bash msg"
  fatal "test bash msg" 1
fi